CREATE DATABASE IF NOT EXISTS nutritiondb;
USE nutritiondb;

CREATE TABLE IF NOT EXISTS nutrition (
    nutrition_id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    source_type VARCHAR(100),
    source_details TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
